version: '3.8'

volumes:
  database-data:

services:
  app:
    container_name: stats
    build: .
    restart: unless-stopped
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips='*'
    ports:
      - 8181:8000
    volumes:
      - database-data:/app/db
